require 'slack-nfl-bot/commands/team'
require 'slack-nfl-bot/commands/fact'
require 'slack-nfl-bot/commands/ping'
require 'slack-nfl-bot/commands/about'
require 'slack-nfl-bot/commands/score'
require 'slack-nfl-bot/commands/standings'
require 'slack-nfl-bot/commands/help'
