require 'slack-nfl-bot/models/base'
require 'slack-nfl-bot/models/team'
require 'slack-nfl-bot/models/fact'
require 'slack-nfl-bot/models/week'
require 'slack-nfl-bot/models/game'
require 'slack-nfl-bot/models/standings'
require 'slack-nfl-bot/models/employee_team'
